spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_school?user=root&password=&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    stat-view-servlet:
      enabled: true